"""Update tables structures

Revision ID: a1f38b3b857a
Revises: 9f3af4d0b6ad
Create Date: 2024-06-19 02:50:40.842422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1f38b3b857a'
down_revision = '9f3af4d0b6ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.drop_column('booking_start_date')
        batch_op.drop_column('is_booked')
        batch_op.drop_column('booking_end_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_booked', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('booking_start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
