"""Update tables structures

Revision ID: 756a88dbf1dd
Revises: 9d9509a27e79
Create Date: 2024-06-14 17:36:39.784928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756a88dbf1dd'
down_revision = '9d9509a27e79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
